"""add_ai_analysis_tables

Revision ID: 1df874a2b1e4
Revises: 34d280a60a3f
Create Date: 2025-11-22 15:06:57.393307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1df874a2b1e4'
down_revision: Union[str, None] = '34d280a60a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('analysis_type', sa.Enum('IMAGE', 'LAB_RESULT', 'COMBINED', name='analysistype'), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('ai_provider', sa.Enum('CLAUDE', 'OPENAI', 'CUSTOM', name='aiprovider'), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('prompt_template', sa.String(length=255), nullable=True),
    sa.Column('primary_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('differential_diagnoses', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.Enum('BENIGN', 'MILD', 'MODERATE', 'SEVERE', 'CRITICAL', 'UNKNOWN', name='severity'), nullable=True),
    sa.Column('clinical_findings', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('key_features_identified', sa.JSON(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('lab_values_extracted', sa.JSON(), nullable=True),
    sa.Column('abnormal_values', sa.JSON(), nullable=True),
    sa.Column('reference_ranges', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ACCEPTED', 'REJECTED', 'MODIFIED', name='analysisstatus'), nullable=True),
    sa.Column('doctor_feedback', sa.Text(), nullable=True),
    sa.Column('doctor_modified_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('is_flagged_for_review', sa.Boolean(), nullable=True),
    sa.Column('flagged_reason', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_consultation_id'), 'ai_analyses', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_deleted_at'), 'ai_analyses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ai_analyses_doctor_id'), 'ai_analyses', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_id'), 'ai_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_is_deleted'), 'ai_analyses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_analyses_patient_id'), 'ai_analyses', ['patient_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_status'), 'ai_analyses', ['status'], unique=False)
    op.create_table('ai_analysis_audit_logs',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'VIEWED', 'ACCEPTED', 'REJECTED', 'MODIFIED', 'DELETED', name='auditaction'), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_audit_logs_analysis_id'), 'ai_analysis_audit_logs', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_audit_logs_deleted_at'), 'ai_analysis_audit_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ai_analysis_audit_logs_id'), 'ai_analysis_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_audit_logs_is_deleted'), 'ai_analysis_audit_logs', ['is_deleted'], unique=False)
    op.create_table('ai_analysis_images',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('regions_of_interest', sa.JSON(), nullable=True),
    sa.Column('image_findings', sa.Text(), nullable=True),
    sa.Column('confidence_for_this_image', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_images_analysis_id'), 'ai_analysis_images', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_images_deleted_at'), 'ai_analysis_images', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ai_analysis_images_id'), 'ai_analysis_images', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_images_is_deleted'), 'ai_analysis_images', ['is_deleted'], unique=False)
    # op.drop_table('lesion_locations')
    # op.drop_index('idx_doctor_schedules_doctor_id', table_name='doctor_schedules')
    # op.drop_table('doctor_schedules')
    # op.drop_index('idx_audit_logs_table_record', table_name='audit_logs')
    # op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    # op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    # op.drop_table('audit_logs')
    # op.drop_table('lesion_types')
    # op.drop_index('idx_appointments_doctor_start', table_name='appointments')
    # op.drop_index('idx_appointments_patient_start', table_name='appointments')
    # op.drop_index('idx_appointments_status_start', table_name='appointments')
    # op.drop_constraint('fk_appointments_recurring_series', 'appointments', type_='foreignkey')
    op.alter_column('consultation_images', 'image_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # op.drop_index('idx_images_patient_upload', table_name='consultation_images')
    # op.drop_index('idx_images_storage_type', table_name='consultation_images')
    # op.drop_index('idx_images_storage_type_upload_status', table_name='consultation_images')
    # op.drop_index('idx_images_upload_status', table_name='consultation_images')
    # op.drop_column('consultation_images', 'upload_status')
    # op.drop_column('consultation_images', 's3_object_key')
    # op.drop_column('consultation_images', 'file_path')
    # op.drop_column('consultation_images', 'storage_type')
    # op.drop_index('idx_consultations_doctor_id', table_name='consultations')
    # op.drop_index('idx_consultations_followup', table_name='consultations')
    # op.drop_column('consultations', 'consultation_number')
    op.add_column('lab_results', sa.Column('test_type', sa.Enum('BLOOD', 'BIOPSY', 'CULTURE', 'ALLERGY', 'HORMONE', 'OTHER', name='testtype'), nullable=True))
    op.add_column('lab_results', sa.Column('lab_facility', sa.String(length=255), nullable=True))
    op.add_column('lab_results', sa.Column('raw_data', sa.Text(), nullable=True))
    op.add_column('lab_results', sa.Column('structured_data', sa.JSON(), nullable=True))
    op.add_column('lab_results', sa.Column('file_type', sa.String(length=50), nullable=True))
    op.add_column('lab_results', sa.Column('file_url', sa.String(length=500), nullable=True))
    op.add_column('lab_results', sa.Column('ai_analysis_id', sa.Integer(), nullable=True))
    op.add_column('lab_results', sa.Column('is_manually_entered', sa.Boolean(), nullable=True))
    op.alter_column('lab_results', 'test_name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('idx_lab_results_patient', table_name='lab_results')
    op.drop_index('idx_lab_results_test_date', table_name='lab_results')
    op.create_index(op.f('ix_lab_results_consultation_id'), 'lab_results', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_lab_results_deleted_at'), 'lab_results', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_lab_results_doctor_id'), 'lab_results', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_lab_results_id'), 'lab_results', ['id'], unique=False)
    op.create_index(op.f('ix_lab_results_is_deleted'), 'lab_results', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_lab_results_patient_id'), 'lab_results', ['patient_id'], unique=False)
    op.drop_constraint('lab_results_patient_id_fkey', 'lab_results', type_='foreignkey')
    op.drop_constraint('lab_results_doctor_id_fkey', 'lab_results', type_='foreignkey')
    op.drop_constraint('lab_results_consultation_id_fkey', 'lab_results', type_='foreignkey')
    op.create_foreign_key(None, 'lab_results', 'consultations', ['consultation_id'], ['id'])
    op.create_foreign_key(None, 'lab_results', 'users', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'lab_results', 'ai_analyses', ['ai_analysis_id'], ['id'])
    op.create_foreign_key(None, 'lab_results', 'patients', ['patient_id'], ['id'])
    op.drop_column('lab_results', 'notes')
    op.drop_column('lab_results', 'interpretation')
    op.drop_column('lab_results', 'result_value')
    op.drop_column('lab_results', 'unit')
    op.drop_column('lab_results', 'normal')
    op.drop_column('lab_results', 'reference_range')
    op.drop_index('idx_patients_doctor_deleted', table_name='patients')
    op.drop_index('idx_patients_doctor_id', table_name='patients')
    op.drop_index('idx_prescriptions_delivery', table_name='prescriptions')
    op.drop_index('idx_prescriptions_valid_until', table_name='prescriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_prescriptions_valid_until', 'prescriptions', ['valid_until'], unique=False)
    op.create_index('idx_prescriptions_delivery', 'prescriptions', ['is_delivered', 'patient_id'], unique=False)
    op.create_index('idx_patients_doctor_id', 'patients', ['doctor_id'], unique=False)
    op.create_index('idx_patients_doctor_deleted', 'patients', ['doctor_id', 'is_deleted'], unique=False)
    op.add_column('lab_results', sa.Column('reference_range', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('normal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('result_value', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('interpretation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.create_foreign_key('lab_results_consultation_id_fkey', 'lab_results', 'consultations', ['consultation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('lab_results_doctor_id_fkey', 'lab_results', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('lab_results_patient_id_fkey', 'lab_results', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_lab_results_patient_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_is_deleted'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_doctor_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_deleted_at'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_consultation_id'), table_name='lab_results')
    op.create_index('idx_lab_results_test_date', 'lab_results', [sa.text('test_date DESC')], unique=False)
    op.create_index('idx_lab_results_patient', 'lab_results', ['patient_id'], unique=False)
    op.alter_column('lab_results', 'test_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('lab_results', 'is_manually_entered')
    op.drop_column('lab_results', 'ai_analysis_id')
    op.drop_column('lab_results', 'file_url')
    op.drop_column('lab_results', 'file_type')
    op.drop_column('lab_results', 'structured_data')
    op.drop_column('lab_results', 'raw_data')
    op.drop_column('lab_results', 'lab_facility')
    op.drop_column('lab_results', 'test_type')
    op.add_column('consultations', sa.Column('consultation_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('idx_consultations_followup', 'consultations', ['follow_up_required', 'follow_up_date'], unique=False)
    op.create_index('idx_consultations_doctor_id', 'consultations', ['doctor_id'], unique=False)
    op.add_column('consultation_images', sa.Column('storage_type', postgresql.ENUM('base64', 's3', name='storage_type_enum'), server_default=sa.text("'base64'::storage_type_enum"), autoincrement=False, nullable=False))
    op.add_column('consultation_images', sa.Column('file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('consultation_images', sa.Column('s3_object_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('consultation_images', sa.Column('upload_status', postgresql.ENUM('pending', 'completed', 'failed', name='upload_status_enum'), server_default=sa.text("'completed'::upload_status_enum"), autoincrement=False, nullable=False))
    op.create_index('idx_images_upload_status', 'consultation_images', ['upload_status'], unique=False)
    op.create_index('idx_images_storage_type_upload_status', 'consultation_images', ['storage_type', 'upload_status'], unique=False)
    op.create_index('idx_images_storage_type', 'consultation_images', ['storage_type'], unique=False)
    op.create_index('idx_images_patient_upload', 'consultation_images', ['patient_id', sa.text('uploaded_at DESC')], unique=False)
    op.alter_column('consultation_images', 'image_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key('fk_appointments_recurring_series', 'appointments', 'appointments', ['recurring_series_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_appointments_status_start', 'appointments', ['status', sa.text('start_time DESC')], unique=False)
    op.create_index('idx_appointments_patient_start', 'appointments', ['patient_id', sa.text('start_time DESC')], unique=False)
    op.create_index('idx_appointments_doctor_start', 'appointments', ['doctor_id', sa.text('start_time DESC')], unique=False)
    op.create_table('lesion_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('icd_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lesion_types_pkey'),
    sa.UniqueConstraint('name', name='uq_lesion_types_name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('changes_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'success'::character varying"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_logs_table_record', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('break_start', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('break_end', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('is_working', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('start_time < end_time', name='ck_doctor_schedules_time'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='doctor_schedules_doctor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='doctor_schedules_pkey'),
    sa.UniqueConstraint('doctor_id', 'day_of_week', name='uq_doctor_schedules_day')
    )
    op.create_index('idx_doctor_schedules_doctor_id', 'doctor_schedules', ['doctor_id'], unique=False)
    op.create_table('lesion_locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('body_part', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lesion_locations_pkey'),
    sa.UniqueConstraint('name', name='uq_lesion_locations_name')
    )
    op.drop_index(op.f('ix_ai_analysis_images_is_deleted'), table_name='ai_analysis_images')
    op.drop_index(op.f('ix_ai_analysis_images_id'), table_name='ai_analysis_images')
    op.drop_index(op.f('ix_ai_analysis_images_deleted_at'), table_name='ai_analysis_images')
    op.drop_index(op.f('ix_ai_analysis_images_analysis_id'), table_name='ai_analysis_images')
    op.drop_table('ai_analysis_images')
    op.drop_index(op.f('ix_ai_analysis_audit_logs_is_deleted'), table_name='ai_analysis_audit_logs')
    op.drop_index(op.f('ix_ai_analysis_audit_logs_id'), table_name='ai_analysis_audit_logs')
    op.drop_index(op.f('ix_ai_analysis_audit_logs_deleted_at'), table_name='ai_analysis_audit_logs')
    op.drop_index(op.f('ix_ai_analysis_audit_logs_analysis_id'), table_name='ai_analysis_audit_logs')
    op.drop_table('ai_analysis_audit_logs')
    op.drop_index(op.f('ix_ai_analyses_status'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_patient_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_is_deleted'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_doctor_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_deleted_at'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_consultation_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
