"""add_ai_analysis_tables

Revision ID: 1df874a2b1e4
Revises: 34d280a60a3f
Create Date: 2025-11-22 15:06:57.393307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1df874a2b1e4'
down_revision: Union[str, None] = '34d280a60a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('analysis_type', sa.Enum('IMAGE', 'LAB_RESULT', 'COMBINED', name='analysistype'), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=True),
    sa.Column('ai_provider', sa.Enum('CLAUDE', 'OPENAI', 'CUSTOM', name='aiprovider'), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('prompt_template', sa.String(length=255), nullable=True),
    sa.Column('primary_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('differential_diagnoses', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('severity', sa.Enum('BENIGN', 'MILD', 'MODERATE', 'SEVERE', 'CRITICAL', 'UNKNOWN', name='severity'), nullable=True),
    sa.Column('clinical_findings', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('key_features_identified', sa.JSON(), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('lab_values_extracted', sa.JSON(), nullable=True),
    sa.Column('abnormal_values', sa.JSON(), nullable=True),
    sa.Column('reference_ranges', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'ACCEPTED', 'REJECTED', 'MODIFIED', name='analysisstatus'), nullable=True),
    sa.Column('doctor_feedback', sa.Text(), nullable=True),
    sa.Column('doctor_modified_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('is_flagged_for_review', sa.Boolean(), nullable=True),
    sa.Column('flagged_reason', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_consultation_id'), 'ai_analyses', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_deleted_at'), 'ai_analyses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ai_analyses_doctor_id'), 'ai_analyses', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_id'), 'ai_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_is_deleted'), 'ai_analyses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ai_analyses_patient_id'), 'ai_analyses', ['patient_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_status'), 'ai_analyses', ['status'], unique=False)
    op.create_table('ai_analysis_audit_logs',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'VIEWED', 'ACCEPTED', 'REJECTED', 'MODIFIED', 'DELETED', name='auditaction'), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_audit_logs_analysis_id'), 'ai_analysis_audit_logs', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_audit_logs_deleted_at'), 'ai_analysis_audit_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ai_analysis_audit_logs_id'), 'ai_analysis_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_audit_logs_is_deleted'), 'ai_analysis_audit_logs', ['is_deleted'], unique=False)
    op.create_table('ai_analysis_images',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('regions_of_interest', sa.JSON(), nullable=True),
    sa.Column('image_findings', sa.Text(), nullable=True),
    sa.Column('confidence_for_this_image', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['ai_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_images_analysis_id'), 'ai_analysis_images', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_images_deleted_at'), 'ai_analysis_images', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ai_analysis_images_id'), 'ai_analysis_images', ['id'], unique=False)
    op.create_index(op.f('ix_ai_analysis_images_is_deleted'), 'ai_analysis_images', ['is_deleted'], unique=False)
    # op.drop_table('lesion_locations')
    # op.drop_index('idx_doctor_schedules_doctor_id', table_name='doctor_schedules')
    # op.drop_table('doctor_schedules')
    # op.drop_index('idx_audit_logs_table_record', table_name='audit_logs')
    # op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    # op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    # op.drop_table('audit_logs')
    # op.drop_table('lesion_types')
    # op.drop_index('idx_appointments_doctor_start', table_name='appointments')
    # op.drop_index('idx_appointments_patient_start', table_name='appointments')
    # op.drop_index('idx_appointments_status_start', table_name='appointments')
    # op.drop_constraint('fk_appointments_recurring_series', 'appointments', type_='foreignkey')

    # Drop views that depend on consultation_images to allow batch alteration
    op.execute("DROP VIEW IF EXISTS v_doctor_consultation_stats")
    op.execute("DROP VIEW IF EXISTS v_patient_consultation_history")
    op.execute("DROP VIEW IF EXISTS v_consultation_images")

    with op.batch_alter_table('consultation_images') as batch_op:
        batch_op.alter_column('image_data',
                   existing_type=sa.VARCHAR(),
                   nullable=False)
        # batch_op.drop_index('idx_images_patient_upload')
        # batch_op.drop_index('idx_images_storage_type')
        # batch_op.drop_index('idx_images_storage_type_upload_status')
        # batch_op.drop_index('idx_images_upload_status')
        # batch_op.drop_column('upload_status')
        # batch_op.drop_column('s3_object_key')
        # batch_op.drop_column('file_path')
        # batch_op.drop_column('storage_type')

    # Recreate views
    op.execute("""
        CREATE VIEW v_consultation_images AS
        SELECT * FROM consultation_images
        WHERE is_deleted = false
    """)

    op.execute("""
        CREATE VIEW v_doctor_consultation_stats AS
        SELECT
            u.id as doctor_id,
            u.full_name as doctor_name,
            COUNT(DISTINCT c.id) as total_consultations,
            COUNT(DISTINCT CASE WHEN c.follow_up_required = true THEN c.id END) as follow_up_required_count,
            COUNT(DISTINCT CASE WHEN c.follow_up_required = true AND c.follow_up_date <= date('now')
                THEN c.id END) as overdue_followup_count,
            COUNT(DISTINCT ci.id) as total_images,
            COUNT(DISTINCT p.id) as unique_patients,
            MAX(c.consultation_date) as last_consultation_date
        FROM v_users u
        LEFT JOIN v_consultations c ON u.id = c.doctor_id
        LEFT JOIN v_consultation_images ci ON c.id = ci.consultation_id
        LEFT JOIN v_patients p ON c.patient_id = p.id
        WHERE u.role = 'DOCTOR'
        GROUP BY u.id, u.full_name
        ORDER BY total_consultations DESC
    """)

    op.execute("""
        CREATE VIEW v_patient_consultation_history AS
        SELECT
            p.id as patient_id,
            p.first_name || ' ' || p.last_name as patient_name,
            p.doctor_id,
            u.full_name as doctor_name,
            c.id as consultation_id,
            c.consultation_date,
            c.follow_up_required,
            c.follow_up_date,
            c.diagnosis,
            COUNT(DISTINCT ci.id) as image_count,
            ROW_NUMBER() OVER (PARTITION BY p.id ORDER BY c.consultation_date DESC) as recency_rank
        FROM v_patients p
        LEFT JOIN v_users u ON p.doctor_id = u.id
        LEFT JOIN v_consultations c ON p.id = c.patient_id
        LEFT JOIN v_consultation_images ci ON c.id = ci.consultation_id
        WHERE c.id IS NOT NULL
        GROUP BY p.id, p.first_name, p.last_name, p.doctor_id, u.full_name,
                 c.id, c.consultation_date, c.follow_up_required, c.follow_up_date, c.diagnosis
        ORDER BY p.id, c.consultation_date DESC
    """)

    # op.drop_index('idx_consultations_doctor_id', table_name='consultations')
    # op.drop_index('idx_consultations_followup', table_name='consultations')
    # op.drop_column('consultations', 'consultation_number')

    # Drop views that depend on lab_results
    op.execute("DROP VIEW IF EXISTS v_system_health_metrics")
    op.execute("DROP VIEW IF EXISTS v_dashboard_stats")
    op.execute("DROP VIEW IF EXISTS v_lab_results_summary")
    op.execute("DROP VIEW IF EXISTS v_lab_results")

    with op.batch_alter_table('lab_results') as batch_op:
        batch_op.add_column(sa.Column('test_type', sa.Enum('BLOOD', 'BIOPSY', 'CULTURE', 'ALLERGY', 'HORMONE', 'OTHER', name='testtype'), nullable=True))
        batch_op.add_column(sa.Column('lab_facility', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('raw_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('structured_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('ai_analysis_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_manually_entered', sa.Boolean(), nullable=True))
        batch_op.alter_column('test_name',
                   existing_type=sa.VARCHAR(length=200),
                   type_=sa.String(length=255),
                   existing_nullable=False)
        batch_op.drop_index('idx_lab_results_patient')
        batch_op.drop_index('idx_lab_results_test_date')
        batch_op.create_index(op.f('ix_lab_results_consultation_id'), ['consultation_id'], unique=False)
        batch_op.create_index(op.f('ix_lab_results_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(op.f('ix_lab_results_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(op.f('ix_lab_results_id'), ['id'], unique=False)
        batch_op.create_index(op.f('ix_lab_results_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(op.f('ix_lab_results_patient_id'), ['patient_id'], unique=False)
        
        # Add named foreign keys
        batch_op.create_foreign_key('fk_lab_results_consultation_id', 'consultations', ['consultation_id'], ['id'])
        batch_op.create_foreign_key('fk_lab_results_doctor_id', 'users', ['doctor_id'], ['id'])
        batch_op.create_foreign_key('fk_lab_results_ai_analysis_id', 'ai_analyses', ['ai_analysis_id'], ['id'])
        batch_op.create_foreign_key('fk_lab_results_patient_id', 'patients', ['patient_id'], ['id'])
        
        batch_op.drop_column('notes')
        batch_op.drop_column('interpretation')
        batch_op.drop_column('result_value')
        batch_op.drop_column('unit')
        batch_op.drop_column('normal')
        batch_op.drop_column('reference_range')

    # Recreate views
    op.execute("""
        CREATE VIEW v_lab_results AS
        SELECT * FROM lab_results
        WHERE is_deleted = false
    """)

    op.execute("""
        CREATE VIEW v_lab_results_summary AS
        SELECT
            lr.patient_id,
            p.first_name || ' ' || p.last_name as patient_name,
            COUNT(*) as total_tests,
            0 as normal_results,
            0 as abnormal_results,
            0 as pending_results,
            GROUP_CONCAT(DISTINCT lr.test_name) as test_types,
            MAX(lr.test_date) as latest_test_date
        FROM v_lab_results lr
        LEFT JOIN v_patients p ON lr.patient_id = p.id
        GROUP BY lr.patient_id, p.first_name, p.last_name
        ORDER BY abnormal_results DESC, total_tests DESC
    """)

    op.execute("""
        CREATE VIEW v_dashboard_stats AS
        SELECT
            (SELECT COUNT(*) FROM v_patients) as total_patients,
            (SELECT COUNT(*) FROM v_appointments
             WHERE status = 'SCHEDULED' AND start_time > DATE('now')) as upcoming_appointments,
            (SELECT COUNT(*) FROM v_appointments
             WHERE status = 'IN_PROGRESS' AND start_time <= DATE('now') AND end_time > DATE('now')) as current_appointments,
            (SELECT COUNT(*) FROM v_consultations
             WHERE follow_up_required = true AND follow_up_date <= DATE('now')) as pending_followups,
            (SELECT COUNT(*) FROM v_prescriptions
             WHERE is_delivered = false) as undelivered_prescriptions,
            0 as abnormal_lab_results
    """)

    op.execute("""
        CREATE VIEW v_system_health_metrics AS
        SELECT
            (SELECT COUNT(*) FROM v_users WHERE role = 'DOCTOR') as total_doctors,
            (SELECT COUNT(*) FROM v_patients) as total_patients,
            (SELECT COUNT(*) FROM v_appointments WHERE status IN ('SCHEDULED', 'CONFIRMED')) as pending_appointments,
            (SELECT COUNT(*) FROM v_consultations WHERE follow_up_required = true
                AND follow_up_date <= date('now')) as overdue_followups,
            (SELECT COUNT(*) FROM v_prescriptions WHERE is_delivered = false) as undelivered_prescriptions,
            0 as abnormal_lab_results,
            (SELECT COUNT(*) FROM v_appointments
                WHERE status = 'NO_SHOW' AND start_time >= date('now', '-30 days')) as no_shows_this_month,
            (SELECT COUNT(*) FROM audit_logs WHERE timestamp >= date('now')) as audit_events_today,
            datetime('now') as last_updated
    """)

    # op.drop_index('idx_patients_doctor_deleted', table_name='patients')
    # op.drop_index('idx_patients_doctor_id', table_name='patients')
    # op.drop_index('idx_prescriptions_delivery', table_name='prescriptions')
    # op.drop_index('idx_prescriptions_valid_until', table_name='prescriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_prescriptions_valid_until', 'prescriptions', ['valid_until'], unique=False)
    op.create_index('idx_prescriptions_delivery', 'prescriptions', ['is_delivered', 'patient_id'], unique=False)
    op.create_index('idx_patients_doctor_id', 'patients', ['doctor_id'], unique=False)
    op.create_index('idx_patients_doctor_deleted', 'patients', ['doctor_id', 'is_deleted'], unique=False)
    op.add_column('lab_results', sa.Column('reference_range', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('normal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('result_value', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('interpretation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('lab_results', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.drop_constraint(None, 'lab_results', type_='foreignkey')
    op.create_foreign_key('lab_results_consultation_id_fkey', 'lab_results', 'consultations', ['consultation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('lab_results_doctor_id_fkey', 'lab_results', 'users', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('lab_results_patient_id_fkey', 'lab_results', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_lab_results_patient_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_is_deleted'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_doctor_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_deleted_at'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_consultation_id'), table_name='lab_results')
    op.create_index('idx_lab_results_test_date', 'lab_results', [sa.text('test_date DESC')], unique=False)
    op.create_index('idx_lab_results_patient', 'lab_results', ['patient_id'], unique=False)
    op.alter_column('lab_results', 'test_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('lab_results', 'is_manually_entered')
    op.drop_column('lab_results', 'ai_analysis_id')
    op.drop_column('lab_results', 'file_url')
    op.drop_column('lab_results', 'file_type')
    op.drop_column('lab_results', 'structured_data')
    op.drop_column('lab_results', 'raw_data')
    op.drop_column('lab_results', 'lab_facility')
    op.drop_column('lab_results', 'test_type')
    op.add_column('consultations', sa.Column('consultation_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('idx_consultations_followup', 'consultations', ['follow_up_required', 'follow_up_date'], unique=False)
    op.create_index('idx_consultations_doctor_id', 'consultations', ['doctor_id'], unique=False)
    op.add_column('consultation_images', sa.Column('storage_type', postgresql.ENUM('base64', 's3', name='storage_type_enum'), server_default=sa.text("'base64'::storage_type_enum"), autoincrement=False, nullable=False))
    op.add_column('consultation_images', sa.Column('file_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('consultation_images', sa.Column('s3_object_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('consultation_images', sa.Column('upload_status', postgresql.ENUM('pending', 'completed', 'failed', name='upload_status_enum'), server_default=sa.text("'completed'::upload_status_enum"), autoincrement=False, nullable=False))
    op.create_index('idx_images_upload_status', 'consultation_images', ['upload_status'], unique=False)
    op.create_index('idx_images_storage_type_upload_status', 'consultation_images', ['storage_type', 'upload_status'], unique=False)
    op.create_index('idx_images_storage_type', 'consultation_images', ['storage_type'], unique=False)
    op.create_index('idx_images_patient_upload', 'consultation_images', ['patient_id', sa.text('uploaded_at DESC')], unique=False)
    op.alter_column('consultation_images', 'image_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key('fk_appointments_recurring_series', 'appointments', 'appointments', ['recurring_series_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_appointments_status_start', 'appointments', ['status', sa.text('start_time DESC')], unique=False)
    op.create_index('idx_appointments_patient_start', 'appointments', ['patient_id', sa.text('start_time DESC')], unique=False)
    op.create_index('idx_appointments_doctor_start', 'appointments', ['doctor_id', sa.text('start_time DESC')], unique=False)
    op.create_table('lesion_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('icd_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lesion_types_pkey'),
    sa.UniqueConstraint('name', name='uq_lesion_types_name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('changes_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'success'::character varying"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='audit_logs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='audit_logs_pkey')
    )
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('idx_audit_logs_table_record', 'audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('break_start', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('break_end', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('is_working', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('start_time < end_time', name='ck_doctor_schedules_time'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='doctor_schedules_doctor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='doctor_schedules_pkey'),
    sa.UniqueConstraint('doctor_id', 'day_of_week', name='uq_doctor_schedules_day')
    )
    op.create_index('idx_doctor_schedules_doctor_id', 'doctor_schedules', ['doctor_id'], unique=False)
    op.create_table('lesion_locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('body_part', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lesion_locations_pkey'),
    sa.UniqueConstraint('name', name='uq_lesion_locations_name')
    )
    op.drop_index(op.f('ix_ai_analysis_images_is_deleted'), table_name='ai_analysis_images')
    op.drop_index(op.f('ix_ai_analysis_images_id'), table_name='ai_analysis_images')
    op.drop_index(op.f('ix_ai_analysis_images_deleted_at'), table_name='ai_analysis_images')
    op.drop_index(op.f('ix_ai_analysis_images_analysis_id'), table_name='ai_analysis_images')
    op.drop_table('ai_analysis_images')
    op.drop_index(op.f('ix_ai_analysis_audit_logs_is_deleted'), table_name='ai_analysis_audit_logs')
    op.drop_index(op.f('ix_ai_analysis_audit_logs_id'), table_name='ai_analysis_audit_logs')
    op.drop_index(op.f('ix_ai_analysis_audit_logs_deleted_at'), table_name='ai_analysis_audit_logs')
    op.drop_index(op.f('ix_ai_analysis_audit_logs_analysis_id'), table_name='ai_analysis_audit_logs')
    op.drop_table('ai_analysis_audit_logs')
    op.drop_index(op.f('ix_ai_analyses_status'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_patient_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_is_deleted'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_doctor_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_deleted_at'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_consultation_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
