"""add consultation_images table for medical image storage

Revision ID: c00048e390d6
Revises: cfa3c628a5e7
Create Date: 2025-11-14 12:12:05.630741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00048e390d6'
down_revision: Union[str, None] = 'cfa3c628a5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=50), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('image_type', sa.String(length=100), nullable=True),
    sa.Column('body_location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('camera_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_images_consultation_id'), 'consultation_images', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_consultation_images_id'), 'consultation_images', ['id'], unique=False)

    # Drop temporary table if exists (SQLite migration artifact)
    try:
        op.drop_table('_alembic_tmp_consultations')
    except:
        pass

    # Skip foreign key creation as it already exists from previous migration
    # SQLite doesn't support ALTER TABLE ADD CONSTRAINT for existing tables
    # The FK was already created in migration cfa3c628a5e7
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop consultation_images table and indexes
    op.drop_index(op.f('ix_consultation_images_id'), table_name='consultation_images')
    op.drop_index(op.f('ix_consultation_images_consultation_id'), table_name='consultation_images')
    op.drop_table('consultation_images')
    # ### end Alembic commands ###
