"""Activate all model relationships

Revision ID: cfa3c628a5e7
Revises: 5d2385832922
Create Date: 2025-11-14 11:40:59.582624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa3c628a5e7'
down_revision: Union[str, None] = '5d2385832922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_consultations_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_foreign_key('fk_consultations_appointments', 'appointments', ['appointment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_consultations_appointments', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_consultations_appointment_id'))
        batch_op.drop_column('appointment_id')
    # ### end Alembic commands ###
